name: SonarCloud
on:
  push:
    branches: [ "main" ]
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write

jobs:
  scan:
    name: sonar-scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: "20"
          
      - name: Install deps
        run: npm ci
      - name: Test with coverage
        run: npm test -- --coverage --coverageReporters=lcov
